let items=[],currentUser=null,currentFilter='All',reportType='Lost',authMode='login';
const grid=document.querySelector('#itemsGrid'),search=document.querySelector('#searchInput'),categoryFilter=document.querySelector('#categoryFilter'),dialog=document.querySelector('#reportDialog'),toast=document.querySelector('#toast'),authDialog=document.querySelector('#authDialog');
const escapeHtml=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const api=async(path,options={})=>{const response=await fetch(path,{credentials:'same-origin',headers:{'Content-Type':'application/json',...(options.headers||{})},...options});const data=await response.json();if(!response.ok)throw new Error(data.error||'Something went wrong.');return data};
const notify=m=>{toast.textContent=m;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),3200)};
const emoji=category=>({Electronics:'💻',Accessories:'👜',Keys:'🔑',Documents:'🪪',Clothing:'🧥','Books & stationery':'📘',Jewellery:'💍','Sports & fitness':'🏏',Other:'📦'}[category]||'📦');
const tone=category=>({Electronics:'tone-b',Accessories:'tone-a',Keys:'tone-c',Documents:'tone-d',Clothing:'tone-d','Books & stationery':'tone-b',Jewellery:'tone-c','Sports & fitness':'tone-c'}[category]||'tone-a');
function renderItems(){const q=search.value.trim().toLowerCase();const list=items.filter(i=>(currentFilter==='All'||i.type===currentFilter)&&(categoryFilter.value==='All'||i.category===categoryFilter.value)&&`${i.name} ${i.category} ${i.location}`.toLowerCase().includes(q));grid.innerHTML=list.length?list.map(i=>`<article class="item-card"><div class="card-image ${i.type.toLowerCase()} ${tone(i.category)}">${emoji(i.category)}</div><div class="card-content"><p class="category">${escapeHtml(i.category.toUpperCase())}</p><h3>${escapeHtml(i.name)}</h3><div class="card-meta"><span>⌖ ${escapeHtml(i.location)}</span><span>${new Date(i.created_at+'Z').toLocaleDateString()}</span></div></div><button class="item-action" data-connect-item="${i.id}">Request connection →</button></article>`).join(''):'<p class="empty">No reports found. Be the first to report a lost or found item.</p>'}
async function loadItems(){try{items=(await api('/api/items')).items;renderItems()}catch(e){notify('Could not load reports. Start the server and refresh the page.')}};
function syncUser(){const signed=!!currentUser;document.querySelector('#openAuth').classList.toggle('hidden',signed);document.querySelector('#profileButton').classList.toggle('hidden',!signed);document.querySelector('#openConnections').classList.toggle('hidden',!signed);if(signed){profileName.textContent=currentUser.name;profileRole.textContent=currentUser.role==='admin'?'Administrator':currentUser.campus_role;avatarInitials.textContent=currentUser.name.split(' ').map(x=>x[0]).join('').slice(0,2).toUpperCase()}}
function setType(type){reportType=type;document.querySelectorAll('.type-choice').forEach(b=>b.classList.toggle('active',b.dataset.type===type));modalTitle.textContent=`Report a ${type.toLowerCase()} item`;submitReport.innerHTML=`Publish ${type.toLowerCase()} report <span>→</span>`}
function openReport(type){if(!currentUser){authDialog.showModal();notify('Please sign in to publish a report.');return}setType(type);dialog.showModal()}
function setAuthMode(mode){authMode=mode;document.querySelectorAll('.auth-tab').forEach(b=>b.classList.toggle('active',b.dataset.authMode===mode));document.querySelectorAll('.signup-field').forEach(x=>x.classList.toggle('show',mode==='signup'));document.querySelector('#authForm button').innerHTML=`${mode==='login'?'Sign in':'Create account'} <span>→</span>`;authError.textContent=''}
function openConnection(itemId){if(!currentUser){authDialog.showModal();notify('Please sign in to request a connection.');return}connectForm.itemId.value=itemId;connectDialog.showModal()}
async function openConnections(){if(!currentUser)return;try{const list=(await api('/api/connections')).connections;const mine=c=>c.recipient_email===currentUser.email;const card=(c,incoming)=>`<article class="connection-card"><h3>${escapeHtml(c.item_name)}</h3><small>${incoming?`Request from ${escapeHtml(c.sender_name)}`:`Your request to ${escapeHtml(c.recipient_name)}`}</small><p>${escapeHtml(c.message)}</p>${incoming&&c.status==='Pending'?`<div class="connection-actions"><button class="accept-request" data-request-action="Accepted" data-request-id="${c.id}">Accept connection</button><button class="decline-request" data-request-action="Declined" data-request-id="${c.id}">Decline</button></div>`:`<span class="request-status ${c.status==='Accepted'?'accepted':''}">${c.status==='Accepted'?`Connected · ${escapeHtml(incoming?c.sender_email:c.recipient_email)}`:escapeHtml(c.status)}</span>`}</article>`;const received=list.filter(mine),sent=list.filter(c=>!mine(c));connectionsList.innerHTML=(received.length||sent.length)?`${received.length?`<p class="eyebrow"><span></span> RECEIVED</p>${received.map(c=>card(c,true)).join('')}`:''}${sent.length?`<p class="eyebrow connection-sent"><span></span> SENT</p>${sent.map(c=>card(c,false)).join('')}`:''}`:'<p class="empty-connections">No connection requests yet. Browse an item and send a safe request when you see a potential match.</p>';connectionsDialog.showModal()}catch(e){notify(e.message)}}
async function openAdmin(){try{const data=await api('/api/admin/overview');adminItemCount.textContent=data.stats.reports;adminLostCount.textContent=data.stats.lost;adminFoundCount.textContent=data.stats.found;adminReports.innerHTML=data.items.map(i=>`<article class="admin-row"><div><b>${escapeHtml(i.name)}</b><small>${escapeHtml(i.category)} · ${escapeHtml(i.location)}</small></div><em class="${i.type.toLowerCase()}">${i.type.toUpperCase()}</em><small>${escapeHtml(i.owner_name)}</small></article>`).join('');adminDialog.showModal()}catch(e){notify(e.message)}}

document.querySelectorAll('[data-open-report]').forEach(b=>b.addEventListener('click',()=>openReport(b.dataset.openReport)));document.querySelectorAll('.type-choice').forEach(b=>b.addEventListener('click',()=>setType(b.dataset.type)));document.querySelectorAll('.filter[data-filter]').forEach(b=>b.addEventListener('click',()=>{currentFilter=b.dataset.filter;document.querySelectorAll('.filter[data-filter]').forEach(x=>x.classList.toggle('active',x===b));renderItems()}));search.addEventListener('input',renderItems);categoryFilter.addEventListener('change',renderItems);grid.addEventListener('click',e=>{const b=e.target.closest('[data-connect-item]');if(b)openConnection(Number(b.dataset.connectItem))});
reportForm.addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();const d=new FormData(reportForm);try{await api('/api/items',{method:'POST',body:JSON.stringify({name:d.get('name'),category:d.get('category'),location:d.get('location'),date:d.get('date'),description:d.get('description'),type:reportType})});dialog.close();reportForm.reset();await loadItems();notify('Your report is now live for the VCTM community.')}catch(err){notify(err.message)}});
openAuth.addEventListener('click',()=>authDialog.showModal());document.querySelector('.auth-close').addEventListener('click',()=>authDialog.close());document.querySelectorAll('.auth-tab').forEach(b=>b.addEventListener('click',()=>setAuthMode(b.dataset.authMode)));authForm.addEventListener('submit',async e=>{e.preventDefault();const d=new FormData(authForm);try{const payload=authMode==='signup'?{name:d.get('fullName'),campus_role:d.get('campusRole'),email:d.get('email'),password:d.get('password')}:{email:d.get('email'),password:d.get('password')};currentUser=(await api(authMode==='signup'?'/api/register':'/api/login',{method:'POST',body:JSON.stringify(payload)})).user;authDialog.close();authForm.reset();syncUser();notify(`Welcome, ${currentUser.name}.`);if(currentUser.role==='admin')openAdmin()}catch(err){authError.textContent=err.message}});
connectForm.addEventListener('submit',async e=>{if(e.submitter?.value==='cancel')return;e.preventDefault();try{await api('/api/connections',{method:'POST',body:JSON.stringify({item_id:Number(connectForm.itemId.value),message:connectForm.message.value})});connectDialog.close();connectForm.reset();notify('Connection request sent safely to the reporter.')}catch(err){notify(err.message)}});openConnections.addEventListener('click',openConnections);closeConnections.addEventListener('click',()=>connectionsDialog.close());connectionsList.addEventListener('click',async e=>{const b=e.target.closest('[data-request-action]');if(!b)return;try{await api(`/api/connections/${b.dataset.requestId}/status`,{method:'POST',body:JSON.stringify({status:b.dataset.requestAction})});notify(`Connection ${b.dataset.requestAction.toLowerCase()}.`);openConnections()}catch(err){notify(err.message)}});
profileButton.addEventListener('click',()=>currentUser?.role==='admin'?openAdmin():openConnections());closeAdmin.addEventListener('click',()=>adminDialog.close());signOut.addEventListener('click',async()=>{await api('/api/logout',{method:'POST'});currentUser=null;adminDialog.close();syncUser();notify('You have been signed out.')});notifications.addEventListener('click',()=>currentUser?openConnections():notify('Sign in to receive connection updates.'));locationFilter.addEventListener('click',()=>navigator.geolocation?navigator.geolocation.getCurrentPosition(()=>notify('Location support is ready. Add campus coordinates to enable distance filtering.'),()=>notify('Location access was not available.')):notify('Location access is not supported in this browser.'));
(async()=>{try{currentUser=(await api('/api/session')).user;syncUser();await loadItems();setInterval(loadItems,10000)}catch(e){notify('Open this project through http://localhost:8000, not as a file.')}})();
