services:
  - type: web
    name: vctm-foundly
    env: python
    buildCommand: pip install -r requirements.txt || true
    startCommand: python3 server.py
    plan: free
    envVars:
      - key: ALLOWED_DOMAINS
        value: vctm.in,vctm.edu
