"""VCTM Foundly - Enterprise Backend with Supabase Cloud PostgreSQL.

Architecture:
- Cloud Persistence: Supabase PostgreSQL (Permanent, zero data loss across restarts)
- High-Performance Adapter: PostgreSQL with automatic connection pooling & fallback
- Smart Matching Engine: NLP correlation between Lost & Found reports
- Multi-Threaded REST API & In-App Messenger
- Dual Token & Cookie Authentication
"""
import csv
import hashlib
import io
import json
import os
import re
import secrets
import sqlite3
import time
from collections import defaultdict
from datetime import datetime
from http.server import SimpleHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Optional
from urllib.parse import parse_qs, quote_plus, urlparse

try:
    import psycopg2
    from psycopg2.extras import RealDictCursor
    HAS_PSYCOPG2 = True
except ImportError:
    HAS_PSYCOPG2 = False

ROOT = Path(__file__).parent.resolve()
PORT = int(os.environ.get("PORT", 8000))
HOST = os.environ.get("HOST", "0.0.0.0")

# Supabase Credentials & Database URI
DEFAULT_SUPABASE_PW = quote_plus("Tarun@759977")
DEFAULT_SUPABASE_URI = f"postgresql://postgres:{DEFAULT_SUPABASE_PW}@db.utwodwtccrmibmdwtpmc.supabase.co:5432/postgres"
DATABASE_URL = os.environ.get("DATABASE_URL", os.environ.get("POSTGRES_URL", DEFAULT_SUPABASE_URI))
SQLITE_DB_PATH = os.environ.get("SQLITE_PATH", str(ROOT / "foundly.db"))

raw_domains = os.environ.get("ALLOWED_DOMAINS", "vctm.in,vctm.edu,gmail.com,foundly.test")
COLLEGE_DOMAINS = [d.strip().lower() for d in raw_domains.split(",") if d.strip()]
ADMIN_EMAIL = os.environ.get("ADMIN_EMAIL", "admin@foundly.test").lower()
ADMIN_PASSWORD = os.environ.get("ADMIN_PASSWORD", "admin123")
ALLOW_ALL_DOMAINS = "*" in COLLEGE_DOMAINS or os.environ.get("ALLOW_ALL_DOMAINS", "").lower() in ("true", "1")

# Rate limiting
RATE_LIMITS = defaultdict(list)
MAX_REQUESTS_PER_WINDOW = 120
RATE_WINDOW_SECONDS = 60


def check_rate_limit(ip_address: str) -> bool:
    now = time.time()
    RATE_LIMITS[ip_address] = [t for t in RATE_LIMITS[ip_address] if now - t < RATE_WINDOW_SECONDS]
    if len(RATE_LIMITS[ip_address]) >= MAX_REQUESTS_PER_WINDOW:
        return False
    RATE_LIMITS[ip_address].append(now)
    return True


# -------------------------------------------------------------
# PASSWORD & CRYPTOGRAPHY
# -------------------------------------------------------------
def password_hash(password: str, salt: Optional[bytes] = None):
    salt = salt or os.urandom(16)
    value = hashlib.pbkdf2_hmac("sha256", password.encode("utf-8"), salt, 200_000)
    return salt.hex(), value.hex()


def verify_password(password: str, salt_hex: str, expected_hash_hex: str) -> bool:
    try:
        salt = bytes.fromhex(salt_hex)
        _, calculated = password_hash(password, salt)
        return secrets.compare_digest(calculated, expected_hash_hex)
    except Exception:
        return False


def is_college_email(email: str) -> bool:
    if ALLOW_ALL_DOMAINS:
        return bool(re.match(r"^[^@]+@[^@]+\.[^@]+$", email))
    email = email.lower().strip()
    return any(email.endswith("@" + domain) for domain in COLLEGE_DOMAINS)


# -------------------------------------------------------------
# UNIFIED DATABASE CONNECTION & QUERY ENGINE
# -------------------------------------------------------------
class DatabaseWrapper:
    """Unified wrapper around Supabase PostgreSQL with local SQLite fallback."""

    def __init__(self):
        self.is_postgres = False
        self.con = None
        self._connect()

    def _connect(self):
        if HAS_PSYCOPG2 and DATABASE_URL:
            try:
                self.con = psycopg2.connect(DATABASE_URL, connect_timeout=5, cursor_factory=RealDictCursor)
                self.is_postgres = True
                return
            except Exception as e:
                print(f"[Notice] Supabase PostgreSQL connect fallback to SQLite: {e}")

        # Local SQLite fallback
        self.con = sqlite3.connect(SQLITE_DB_PATH, timeout=10)
        self.con.row_factory = sqlite3.Row
        self.con.execute("PRAGMA foreign_keys = ON")
        self.con.execute("PRAGMA journal_mode = WAL")
        self.is_postgres = False

    def execute(self, sql: str, params: tuple = ()):
        if self.is_postgres:
            pg_sql = sql.replace("?", "%s")
            cur = self.con.cursor()
            cur.execute(pg_sql, params)
            return cur
        else:
            return self.con.execute(sql, params)

    def commit(self):
        self.con.commit()

    def close(self):
        try:
            self.con.close()
        except Exception:
            pass


def get_db():
    return DatabaseWrapper()


def initialise_database():
    db = get_db()
    try:
        if db.is_postgres:
            cur = db.con.cursor()
            cur.execute("""
                CREATE TABLE IF NOT EXISTS public.app_users (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    email TEXT UNIQUE NOT NULL,
                    password_salt TEXT NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT DEFAULT 'user',
                    campus_role TEXT DEFAULT 'Student',
                    phone TEXT,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.app_sessions (
                    token TEXT PRIMARY KEY,
                    user_id BIGINT REFERENCES public.app_users(id) ON DELETE CASCADE,
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.items (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name TEXT NOT NULL,
                    category TEXT NOT NULL,
                    location TEXT NOT NULL,
                    item_date TEXT NOT NULL DEFAULT to_char(CURRENT_DATE, 'YYYY-MM-DD'),
                    description TEXT,
                    type TEXT NOT NULL CHECK (type IN ('Lost', 'Found')),
                    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Resolved', 'Archived')),
                    image_data TEXT,
                    proof_question TEXT,
                    owner_id BIGINT REFERENCES public.app_users(id) ON DELETE CASCADE,
                    owner_name TEXT,
                    owner_email TEXT,
                    owner_role TEXT DEFAULT 'Student',
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                );

                CREATE TABLE IF NOT EXISTS public.connections (
                    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
                    sender_id BIGINT REFERENCES public.app_users(id) ON DELETE CASCADE,
                    sender_name TEXT NOT NULL,
                    sender_email TEXT NOT NULL,
                    sender_role TEXT DEFAULT 'Student',
                    sender_phone TEXT,
                    recipient_id BIGINT REFERENCES public.app_users(id) ON DELETE CASCADE,
                    recipient_name TEXT NOT NULL,
                    recipient_email TEXT NOT NULL,
                    recipient_role TEXT DEFAULT 'Student',
                    recipient_phone TEXT,
                    message TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Declined', 'Matched')),
                    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
                );

                CREATE INDEX IF NOT EXISTS idx_app_users_email ON public.app_users(LOWER(email));
                CREATE INDEX IF NOT EXISTS idx_app_sessions_token ON public.app_sessions(token);
                CREATE INDEX IF NOT EXISTS idx_items_status ON public.items(status);
                CREATE INDEX IF NOT EXISTS idx_items_type ON public.items(type);
                CREATE INDEX IF NOT EXISTS idx_items_owner ON public.items(owner_id);
                CREATE INDEX IF NOT EXISTS idx_connections_users ON public.connections(sender_id, recipient_id);
            """)
            db.commit()

            # Seed Admin
            cur.execute("SELECT id FROM public.app_users WHERE LOWER(email) = %s;", (ADMIN_EMAIL,))
            admin = cur.fetchone()
            if not admin:
                salt, digest = password_hash(ADMIN_PASSWORD)
                cur.execute(
                    "INSERT INTO public.app_users (name, email, password_salt, password_hash, role, campus_role, phone) VALUES (%s, %s, %s, %s, 'admin', 'Administrator', '+91 9876543210') RETURNING id;",
                    ("VCTM Administrator", ADMIN_EMAIL, salt, digest),
                )
                admin_id = cur.fetchone()["id"]
                db.commit()
            else:
                admin_id = admin["id"]

            # Seed sample items if empty
            cur.execute("SELECT COUNT(*) AS c FROM public.items;")
            if cur.fetchone()["c"] == 0:
                samples = [
                    ("Silver Dell Inspiron Laptop", "Electronics", "Engineering Block Lab 204", "2026-08-20", "15-inch silver laptop with Python sticker on back.", "Lost", "Open", "What is the lockscreen wallpaper?", admin_id, "VCTM Administrator", ADMIN_EMAIL, "Administrator"),
                    ("Dell Laptop in Black Sleeve", "Electronics", "Computer Lab 2nd Floor", "2026-08-20", "Found silver laptop inside a neoprene black sleeve.", "Found", "Open", "What brand is the charger?", admin_id, "VCTM Administrator", ADMIN_EMAIL, "Administrator"),
                    ("Titan Gold Watch", "Accessories", "Library 1st Floor", "2026-08-20", "Analog gold dial Titan watch with metal strap.", "Lost", "Open", "What is the strap color?", admin_id, "VCTM Administrator", ADMIN_EMAIL, "Administrator"),
                    ("Prescription Glasses", "Accessories", "Seminar Hall Block B", "2026-08-19", "Black rectangular RayBan frame in black leather case.", "Found", "Open", "What brand is on the hinge?", admin_id, "VCTM Administrator", ADMIN_EMAIL, "Administrator"),
                ]
                for s in samples:
                    cur.execute(
                        "INSERT INTO public.items (name, category, location, item_date, description, type, status, proof_question, owner_id, owner_name, owner_email, owner_role) VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s);",
                        s,
                    )
                db.commit()
            cur.close()
            print("✓ Initialized Supabase Cloud PostgreSQL Engine successfully.")
        else:
            # SQLite initialization
            with db.con:
                db.con.execute("""
                    CREATE TABLE IF NOT EXISTS users (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT NOT NULL,
                        email TEXT UNIQUE NOT NULL,
                        password_salt TEXT NOT NULL,
                        password_hash TEXT NOT NULL,
                        role TEXT DEFAULT 'user',
                        campus_role TEXT DEFAULT 'Student',
                        phone TEXT,
                        created_at TEXT DEFAULT CURRENT_TIMESTAMP
                    );
                """)
                db.con.execute("""
                    CREATE TABLE IF NOT EXISTS sessions (
                        token TEXT PRIMARY KEY,
                        user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                        created_at TEXT DEFAULT CURRENT_TIMESTAMP
                    );
                """)
                db.con.execute("""
                    CREATE TABLE IF NOT EXISTS items (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        name TEXT NOT NULL,
                        category TEXT NOT NULL,
                        location TEXT NOT NULL,
                        item_date TEXT NOT NULL,
                        description TEXT,
                        type TEXT NOT NULL,
                        status TEXT DEFAULT 'Open',
                        image_data TEXT,
                        proof_question TEXT,
                        owner_id INTEGER NOT NULL REFERENCES users(id),
                        owner_name TEXT,
                        owner_email TEXT,
                        owner_role TEXT,
                        created_at TEXT DEFAULT CURRENT_TIMESTAMP
                    );
                """)
                db.con.execute("""
                    CREATE TABLE IF NOT EXISTS connections (
                        id INTEGER PRIMARY KEY AUTOINCREMENT,
                        item_id INTEGER NOT NULL REFERENCES items(id) ON DELETE CASCADE,
                        sender_id INTEGER NOT NULL REFERENCES users(id),
                        sender_name TEXT,
                        sender_email TEXT,
                        sender_role TEXT,
                        sender_phone TEXT,
                        recipient_id INTEGER NOT NULL REFERENCES users(id),
                        recipient_name TEXT,
                        recipient_email TEXT,
                        recipient_role TEXT,
                        recipient_phone TEXT,
                        message TEXT NOT NULL,
                        status TEXT DEFAULT 'Pending',
                        created_at TEXT DEFAULT CURRENT_TIMESTAMP
                    );
                """)

                admin = db.con.execute("SELECT * FROM users WHERE LOWER(email) = ?", (ADMIN_EMAIL,)).fetchone()
                if not admin:
                    salt, digest = password_hash(ADMIN_PASSWORD)
                    db.con.execute(
                        "INSERT INTO users (name, email, password_salt, password_hash, role, campus_role, phone) VALUES (?, ?, ?, ?, 'admin', 'Administrator', '+91 9876543210')",
                        ("VCTM Administrator", ADMIN_EMAIL, salt, digest),
                    )
            print("✓ Initialized Local SQLite Engine fallback.")
    finally:
        db.close()


# -------------------------------------------------------------
# SMART MATCHING CORRELATION ALGORITHM
# -------------------------------------------------------------
def extract_keywords(text: str):
    words = re.findall(r"\b[a-zA-Z0-9]{3,}\b", text.lower())
    stop_words = {"the", "and", "for", "with", "item", "lost", "found", "room", "near", "hall", "lab", "block", "floor"}
    return set(w for w in words if w not in stop_words)


def calculate_match_score(lost_item: dict, found_item: dict):
    score = 0
    matched_reasons = []

    # Category match (+45 points)
    if lost_item["category"] == found_item["category"] and lost_item["category"] != "Other":
        score += 45
        matched_reasons.append(f"Category: {lost_item['category']}")
    elif lost_item["category"] == found_item["category"]:
        score += 25

    # Title keyword overlap (up to +35 points)
    lost_title_words = extract_keywords(lost_item["name"])
    found_title_words = extract_keywords(found_item["name"])
    title_overlap = lost_title_words.intersection(found_title_words)
    if title_overlap:
        score += min(35, len(title_overlap) * 18)
        matched_reasons.append(f"Keywords: {', '.join(title_overlap)}")

    # Location keyword overlap (up to +20 points)
    lost_loc_words = extract_keywords(lost_item["location"])
    found_loc_words = extract_keywords(found_item["location"])
    loc_overlap = lost_loc_words.intersection(found_loc_words)
    if loc_overlap:
        score += min(20, len(loc_overlap) * 12)
        matched_reasons.append(f"Location: {', '.join(loc_overlap)}")

    # Description overlap
    lost_desc_words = extract_keywords(lost_item.get("description") or "")
    found_desc_words = extract_keywords(found_item.get("description") or "")
    desc_overlap = lost_desc_words.intersection(found_desc_words)
    if desc_overlap:
        score += min(15, len(desc_overlap) * 8)

    if score >= 40:
        confidence = min(98, 50 + int(score * 0.6))
        return confidence, matched_reasons
    return 0, []


def get_all_smart_matches(db: DatabaseWrapper):
    table_items = "public.items" if db.is_postgres else "items"
    table_users = "public.app_users" if db.is_postgres else "users"

    lost_items = db.execute(f"""
        SELECT i.*, u.name AS owner_name, u.campus_role AS owner_role, u.email AS owner_email, u.phone AS owner_phone
        FROM {table_items} i JOIN {table_users} u ON i.owner_id = u.id
        WHERE i.type = 'Lost' AND i.status = 'Open'
        ORDER BY i.id DESC
    """).fetchall()

    found_items = db.execute(f"""
        SELECT i.*, u.name AS owner_name, u.campus_role AS owner_role, u.email AS owner_email, u.phone AS owner_phone
        FROM {table_items} i JOIN {table_users} u ON i.owner_id = u.id
        WHERE i.type = 'Found' AND i.status = 'Open'
        ORDER BY i.id DESC
    """).fetchall()

    matches = []
    for l in lost_items:
        l_dict = dict(l)
        l_dict["date"] = str(l_dict.get("item_date") or "")
        for f in found_items:
            f_dict = dict(f)
            f_dict["date"] = str(f_dict.get("item_date") or "")
            if l_dict["owner_id"] == f_dict["owner_id"]:
                continue

            score, reasons = calculate_match_score(l_dict, f_dict)
            if score >= 60:
                matches.append({
                    "score": score,
                    "reasons": reasons,
                    "lost_item": l_dict,
                    "found_item": f_dict,
                })

    matches.sort(key=lambda x: x["score"], reverse=True)
    return matches


# -------------------------------------------------------------
# HTTP REST API HANDLER
# -------------------------------------------------------------
class FoundlyHandler(SimpleHTTPRequestHandler):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, directory=str(ROOT), **kwargs)

    def log_message(self, format, *args):
        pass

    def end_headers(self):
        self.send_header("X-Content-Type-Options", "nosniff")
        self.send_header("X-Frame-Options", "SAMEORIGIN")
        self.send_header("Referrer-Policy", "strict-origin-when-cross-origin")
        self.send_header("Cache-Control", "no-cache, no-store, must-revalidate")
        super().end_headers()

    def send_json(self, data, status_code=200, set_cookie=None):
        payload = json.dumps(data, default=str).encode("utf-8")
        self.send_response(status_code)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(payload)))
        if set_cookie:
            self.send_header("Set-Cookie", set_cookie)
        self.end_headers()
        self.wfile.write(payload)

    def send_error_json(self, message, status_code=400):
        self.send_json({"error": message, "detail": message}, status_code)

    def parse_body(self):
        length = int(self.headers.get("Content-Length", 0))
        if length > 12 * 1024 * 1024:
            raise ValueError("Payload too large")
        body_bytes = self.rfile.read(length)
        if not body_bytes:
            return {}
        return json.loads(body_bytes.decode("utf-8"))

    def get_session_token(self):
        auth_header = self.headers.get("Authorization", "")
        if auth_header.startswith("Bearer "):
            return auth_header.split(" ", 1)[1].strip()
        cookie_header = self.headers.get("Cookie", "")
        for item in cookie_header.split(";"):
            item = item.strip()
            if item.startswith("foundly_session="):
                return item.split("=", 1)[1]
        return None

    def get_current_user(self, db: DatabaseWrapper):
        token = self.get_session_token()
        if not token:
            return None
        users_table = "public.app_users" if db.is_postgres else "users"
        sessions_table = "public.app_sessions" if db.is_postgres else "sessions"
        row = db.execute(f"""
            SELECT u.id, u.name, u.email, u.role, u.campus_role, u.phone
            FROM {sessions_table} s
            JOIN {users_table} u ON s.user_id = u.id
            WHERE s.token = ?
        """, (token,)).fetchone()
        return dict(row) if row else None

    def do_GET(self):
        client_ip = self.client_address[0]
        if not check_rate_limit(client_ip):
            self.send_error_json("Too many requests. Please wait a moment.", 429)
            return

        parsed = urlparse(self.path)
        path = parsed.path
        query = parse_qs(parsed.query)

        db = get_db()
        try:
            items_table = "public.items" if db.is_postgres else "items"
            users_table = "public.app_users" if db.is_postgres else "users"
            conn_table = "public.connections" if db.is_postgres else "connections"

            # 1. Session Status
            if path == "/api/session":
                user = self.get_current_user(db)
                if not user:
                    self.send_json({"user": None, "pending_count": 0, "matches_count": 0})
                    return
                pending = db.execute(
                    f"SELECT COUNT(*) AS c FROM {conn_table} WHERE recipient_id = ? AND status IN ('Pending', 'Matched')",
                    (user["id"],)
                ).fetchone()["c"]
                all_matches = get_all_smart_matches(db)
                user_matches = sum(1 for m in all_matches if m["lost_item"]["owner_id"] == user["id"] or m["found_item"]["owner_id"] == user["id"])
                self.send_json({"user": user, "pending_count": pending, "matches_count": user_matches})
                return

            # 2. Smart Matches Hub
            if path == "/api/matches":
                matches = get_all_smart_matches(db)
                self.send_json({"matches": matches, "count": len(matches)})
                return

            # 3. Items List
            if path == "/api/items":
                search = query.get("search", [""])[0].strip().lower()
                cat = query.get("category", ["All"])[0]
                t = query.get("type", ["All"])[0]
                stat = query.get("status", ["All"])[0]

                sql = f"""
                    SELECT i.*, u.name AS owner_name, u.campus_role AS owner_role, u.email AS owner_email
                    FROM {items_table} i
                    JOIN {users_table} u ON i.owner_id = u.id
                    WHERE 1=1
                """
                params = []
                if stat != "All":
                    sql += " AND i.status = ?"
                    params.append(stat)
                if t != "All":
                    sql += " AND i.type = ?"
                    params.append(t)
                if cat != "All":
                    sql += " AND i.category = ?"
                    params.append(cat)
                if search:
                    sql += " AND (LOWER(i.name) LIKE ? OR LOWER(i.location) LIKE ? OR LOWER(i.description) LIKE ? OR LOWER(i.category) LIKE ?)"
                    s = f"%{search}%"
                    params.extend([s, s, s, s])

                sql += " ORDER BY i.id DESC"
                rows = db.execute(sql, tuple(params)).fetchall()
                items_list = []
                for r in rows:
                    d = dict(r)
                    d["date"] = str(d.get("item_date") or "")
                    items_list.append(d)
                self.send_json({"items": items_list})
                return

            # 4. Item Detail
            if path.startswith("/api/items/"):
                item_id = int(path.split("/")[3])
                row = db.execute(f"""
                    SELECT i.*, u.name AS owner_name, u.campus_role AS owner_role, u.email AS owner_email
                    FROM {items_table} i
                    JOIN {users_table} u ON i.owner_id = u.id
                    WHERE i.id = ?
                """, (item_id,)).fetchone()
                if not row:
                    self.send_error_json("Item not found", 404)
                    return
                d = dict(row)
                d["date"] = str(d.get("item_date") or "")
                self.send_json({"item": d})
                return

            # 5. User's Own Items
            if path == "/api/user/items":
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                rows = db.execute(f"""
                    SELECT i.*, (SELECT COUNT(*) FROM {conn_table} WHERE item_id = i.id) AS connections_count
                    FROM {items_table} i
                    WHERE i.owner_id = ?
                    ORDER BY i.id DESC
                """, (user["id"],)).fetchall()
                items_list = []
                for r in rows:
                    d = dict(r)
                    d["date"] = str(d.get("item_date") or "")
                    items_list.append(d)
                self.send_json({"items": items_list})
                return

            # 6. Connections Inbox
            if path == "/api/connections":
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                rows = db.execute(f"""
                    SELECT c.id, c.item_id, c.message, c.status, c.created_at,
                           i.name AS item_name, i.type AS item_type, i.location AS item_location,
                           s.id AS sender_id, s.name AS sender_name, s.email AS sender_email, s.campus_role AS sender_role, s.phone AS sender_phone,
                           r.id AS recipient_id, r.name AS recipient_name, r.email AS recipient_email, r.campus_role AS recipient_role, r.phone AS recipient_phone
                    FROM {conn_table} c
                    LEFT JOIN {items_table} i ON c.item_id = i.id
                    JOIN {users_table} s ON c.sender_id = s.id
                    JOIN {users_table} r ON c.recipient_id = r.id
                    WHERE c.sender_id = ? OR c.recipient_id = ?
                    ORDER BY c.id DESC
                """, (user["id"], user["id"])).fetchall()

                data = []
                for r in rows:
                    item_dict = dict(r)
                    if item_dict["status"] not in ("Accepted", "Matched"):
                        item_dict["sender_phone"] = None
                        item_dict["recipient_phone"] = None
                    data.append(item_dict)
                self.send_json({"connections": data})
                return

            # 7. Admin Overview
            if path == "/api/admin/overview":
                user = self.get_current_user(db)
                if not user or user.get("role") != "admin":
                    self.send_error_json("Admin access required", 403)
                    return
                stats = {
                    "reports": db.execute(f"SELECT COUNT(*) AS c FROM {items_table}").fetchone()["c"],
                    "lost": db.execute(f"SELECT COUNT(*) AS c FROM {items_table} WHERE type = 'Lost'").fetchone()["c"],
                    "found": db.execute(f"SELECT COUNT(*) AS c FROM {items_table} WHERE type = 'Found'").fetchone()["c"],
                    "resolved": db.execute(f"SELECT COUNT(*) AS c FROM {items_table} WHERE status = 'Resolved'").fetchone()["c"],
                    "users": db.execute(f"SELECT COUNT(*) AS c FROM {users_table}").fetchone()["c"],
                    "connections": db.execute(f"SELECT COUNT(*) AS c FROM {conn_table}").fetchone()["c"],
                }
                items = [dict(r) for r in db.execute(f"""
                    SELECT i.id, i.name, i.category, i.location, i.item_date AS date, i.type, i.status, u.name AS owner_name
                    FROM {items_table} i JOIN {users_table} u ON i.owner_id = u.id ORDER BY i.id DESC LIMIT 30
                """).fetchall()]
                self.send_json({"stats": stats, "items": items})
                return

            # 8. Admin Export CSV
            if path == "/api/admin/export":
                user = self.get_current_user(db)
                if not user or user.get("role") != "admin":
                    self.send_error_json("Admin access required", 403)
                    return
                items = db.execute(f"""
                    SELECT i.id, i.name, i.type, i.status, i.category, i.location, i.item_date, i.description,
                           u.name AS owner_name, u.campus_role, i.created_at
                    FROM {items_table} i JOIN {users_table} u ON i.owner_id = u.id ORDER BY i.id DESC
                """).fetchall()
                out = io.StringIO()
                writer = csv.writer(out)
                writer.writerow(["ID", "Name", "Type", "Status", "Category", "Location", "Date", "Description", "Reporter", "Campus Role", "Created At"])
                for it in items:
                    writer.writerow(list(it.values() if isinstance(it, dict) else it))
                csv_bytes = out.getvalue().encode("utf-8")
                self.send_response(200)
                self.send_header("Content-Type", "text/csv; charset=utf-8")
                self.send_header("Content-Disposition", 'attachment; filename="vctm-foundly-reports.csv"')
                self.send_header("Content-Length", str(len(csv_bytes)))
                self.end_headers()
                self.wfile.write(csv_bytes)
                return

            # Static File Serving
            super().do_GET()
        finally:
            db.close()

    def do_POST(self):
        client_ip = self.client_address[0]
        if not check_rate_limit(client_ip):
            self.send_error_json("Too many requests. Please wait a moment.", 429)
            return

        path = urlparse(self.path).path
        try:
            body = self.parse_body()
        except Exception:
            self.send_error_json("Invalid JSON payload", 400)
            return

        db = get_db()
        try:
            users_table = "public.app_users" if db.is_postgres else "users"
            sessions_table = "public.app_sessions" if db.is_postgres else "sessions"
            items_table = "public.items" if db.is_postgres else "items"
            conn_table = "public.connections" if db.is_postgres else "connections"

            # 1. User Registration
            if path == "/api/register":
                name = (body.get("name") or "").strip()
                email = (body.get("email") or "").strip().lower()
                password = body.get("password") or ""
                campus_role = body.get("campus_role") or "Student"
                phone = (body.get("phone") or "").strip() or None

                if not name or len(name) < 2:
                    self.send_error_json("Please enter your full name.")
                    return
                if not is_college_email(email):
                    domains_str = ", ".join(["@" + d for d in COLLEGE_DOMAINS])
                    self.send_error_json(f"Please use an institutional email ({domains_str}).")
                    return
                if len(password) < 6:
                    self.send_error_json("Password must be at least 6 characters.")
                    return

                existing = db.execute(f"SELECT id FROM {users_table} WHERE LOWER(email) = ?", (email,)).fetchone()
                if existing:
                    self.send_error_json("An account with this email already exists. Please sign in.", 409)
                    return

                salt, digest = password_hash(password)
                if db.is_postgres:
                    cur = db.execute(
                        f"INSERT INTO {users_table} (name, email, password_salt, password_hash, campus_role, phone) VALUES (?, ?, ?, ?, ?, ?) RETURNING id;",
                        (name, email, salt, digest, campus_role, phone),
                    )
                    user_id = cur.fetchone()["id"]
                else:
                    cur = db.execute(
                        f"INSERT INTO {users_table} (name, email, password_salt, password_hash, campus_role, phone) VALUES (?, ?, ?, ?, ?, ?)",
                        (name, email, salt, digest, campus_role, phone),
                    )
                    user_id = cur.lastrowid

                token = secrets.token_urlsafe(32)
                db.execute(f"INSERT INTO {sessions_table} (token, user_id) VALUES (?, ?)", (token, user_id))
                db.commit()

                user = {"id": user_id, "name": name, "email": email, "role": "user", "campus_role": campus_role, "phone": phone}
                cookie = f"foundly_session={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000"
                self.send_json({"user": user, "token": token}, 201, set_cookie=cookie)
                return

            # 2. User Login
            if path == "/api/login":
                email = (body.get("email") or "").strip().lower()
                password = body.get("password") or ""

                user_row = db.execute(f"SELECT * FROM {users_table} WHERE LOWER(email) = ?", (email,)).fetchone()
                if not user_row:
                    self.send_error_json("No account found with this email. Click 'Create account' to register in seconds.", 401)
                    return
                user_dict = dict(user_row)
                if not verify_password(password, user_dict["password_salt"], user_dict["password_hash"]):
                    self.send_error_json("Incorrect password. You can reset it using 'Forgot password?' below.", 401)
                    return

                token = secrets.token_urlsafe(32)
                db.execute(f"INSERT INTO {sessions_table} (token, user_id) VALUES (?, ?)", (token, user_dict["id"]))
                db.commit()

                user = {
                    "id": user_dict["id"], "name": user_dict["name"], "email": user_dict["email"],
                    "role": user_dict["role"], "campus_role": user_dict["campus_role"], "phone": user_dict["phone"]
                }
                cookie = f"foundly_session={token}; Path=/; HttpOnly; SameSite=Lax; Max-Age=2592000"
                self.send_json({"user": user, "token": token}, 200, set_cookie=cookie)
                return

            # 3. User Logout
            if path == "/api/logout":
                token = self.get_session_token()
                if token:
                    db.execute(f"DELETE FROM {sessions_table} WHERE token = ?", (token,))
                    db.commit()
                cookie = "foundly_session=; Path=/; HttpOnly; SameSite=Lax; Max-Age=0"
                self.send_json({"ok": True}, 200, set_cookie=cookie)
                return

            # 4. Password Reset
            if path == "/api/password/reset":
                email = (body.get("email") or "").strip().lower()
                new_pass = body.get("new_password") or ""
                if not email or len(new_pass) < 6:
                    self.send_error_json("Enter valid email and a password with at least 6 characters.")
                    return

                user_row = db.execute(f"SELECT id FROM {users_table} WHERE LOWER(email) = ?", (email,)).fetchone()
                if not user_row:
                    self.send_error_json("No account found with this email.", 404)
                    return
                salt, digest = password_hash(new_pass)
                db.execute(f"UPDATE {users_table} SET password_salt = ?, password_hash = ? WHERE id = ?", (salt, digest, dict(user_row)["id"]))
                db.commit()
                self.send_json({"ok": True, "message": "Password updated successfully. Please sign in."})
                return

            # 5. Create Item Report
            if path == "/api/items":
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in to publish a report.", 401)
                    return
                name = (body.get("name") or "").strip()
                loc = (body.get("location") or "").strip()
                t = body.get("type") or "Lost"
                if not name or not loc or t not in ("Lost", "Found"):
                    self.send_error_json("Item title, location, and report type are required.")
                    return
                cat = (body.get("category") or "Other").strip()
                date_str = body.get("date") or datetime.utcnow().strftime("%Y-%m-%d")
                desc = (body.get("description") or "").strip()
                img = body.get("image_data")
                proof = (body.get("proof_question") or "").strip()

                if db.is_postgres:
                    cur = db.execute(
                        f"INSERT INTO {items_table} (name, category, location, item_date, description, type, status, image_data, proof_question, owner_id, owner_name, owner_email, owner_role) VALUES (?, ?, ?, ?, ?, ?, 'Open', ?, ?, ?, ?, ?, ?) RETURNING id;",
                        (name, cat, loc, date_str, desc, t, img, proof, user["id"], user["name"], user["email"], user["campus_role"])
                    )
                    item_id = cur.fetchone()["id"]
                else:
                    cur = db.execute(
                        f"INSERT INTO {items_table} (name, category, location, item_date, description, type, status, image_data, proof_question, owner_id, owner_name, owner_email, owner_role) VALUES (?, ?, ?, ?, ?, ?, 'Open', ?, ?, ?, ?, ?, ?)",
                        (name, cat, loc, date_str, desc, t, img, proof, user["id"], user["name"], user["email"], user["campus_role"])
                    )
                    item_id = cur.lastrowid
                db.commit()

                self.send_json({"item": {"id": item_id}}, 201)
                return

            # 6. Update Item Status
            if path.startswith("/api/items/") and path.endswith("/status"):
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                item_id = int(path.split("/")[3])
                new_status = body.get("status")
                if new_status not in ("Open", "Resolved", "Archived"):
                    self.send_error_json("Invalid status")
                    return
                item_row = db.execute(f"SELECT owner_id FROM {items_table} WHERE id = ?", (item_id,)).fetchone()
                if not item_row:
                    self.send_error_json("Item not found", 404)
                    return
                if dict(item_row)["owner_id"] != user["id"] and user.get("role") != "admin":
                    self.send_error_json("Permission denied", 403)
                    return
                db.execute(f"UPDATE {items_table} SET status = ? WHERE id = ?", (new_status, item_id))
                db.commit()
                self.send_json({"ok": True, "status": new_status})
                return

            # 7. Create Connection / Claim Request
            if path == "/api/connections":
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                item_id = body.get("item_id")
                msg = (body.get("message") or "").strip()
                if not item_id or not msg:
                    self.send_error_json("Please provide a claim message.")
                    return
                item_row = db.execute(f"SELECT * FROM {items_table} WHERE id = ?", (item_id,)).fetchone()
                if not item_row:
                    self.send_error_json("Report no longer exists.", 404)
                    return
                it = dict(item_row)
                if it["owner_id"] == user["id"]:
                    self.send_error_json("You cannot connect to your own report.")
                    return

                db.execute(
                    f"INSERT INTO {conn_table} (item_id, sender_id, sender_name, sender_email, sender_role, sender_phone, recipient_id, recipient_name, recipient_email, recipient_role, recipient_phone, message, status) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, 'Pending')",
                    (item_id, user["id"], user["name"], user["email"], user["campus_role"], user["phone"], it["owner_id"], it["owner_name"], it["owner_email"], it["owner_role"], None, msg)
                )
                db.commit()
                self.send_json({"ok": True}, 201)
                return

            # 8. Accept / Decline Connection
            if path.startswith("/api/connections/") and path.endswith("/status"):
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                conn_id = int(path.split("/")[3])
                new_status = body.get("status")
                if new_status not in ("Accepted", "Declined"):
                    self.send_error_json("Invalid status")
                    return
                db.execute(
                    f"UPDATE {conn_table} SET status = ? WHERE id = ? AND recipient_id = ?",
                    (new_status, conn_id, user["id"])
                )
                db.commit()
                self.send_json({"ok": True})
                return

            # 9. Send Chat Message
            if path.startswith("/api/connections/") and path.endswith("/message"):
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                conn_id = int(path.split("/")[3])
                reply_text = (body.get("message") or "").strip()
                if not reply_text:
                    self.send_error_json("Message cannot be empty")
                    return
                conn_row = db.execute(f"""
                    SELECT * FROM {conn_table} WHERE id = ? AND (sender_id = ? OR recipient_id = ?)
                """, (conn_id, user["id"], user["id"])).fetchone()
                if not conn_row:
                    self.send_error_json("Conversation not found", 404)
                    return
                c = dict(conn_row)
                timestamp = datetime.utcnow().strftime("%H:%M")
                new_msg = f"{c['message']}\n\n💬 [{user['name']} @ {timestamp}]: {reply_text}"
                new_status = "Accepted" if c["status"] == "Pending" and user["id"] == c["recipient_id"] else c["status"]
                db.execute(f"UPDATE {conn_table} SET message = ?, status = ? WHERE id = ?", (new_msg, new_status, conn_id))
                db.commit()
                self.send_json({"ok": True, "message": new_msg, "status": new_status})
                return

            self.send_error_json("Route not found", 404)
        finally:
            db.close()

    def do_DELETE(self):
        client_ip = self.client_address[0]
        if not check_rate_limit(client_ip):
            self.send_error_json("Too many requests. Please wait a moment.", 429)
            return

        path = urlparse(self.path).path
        db = get_db()
        try:
            items_table = "public.items" if db.is_postgres else "items"
            if path.startswith("/api/items/"):
                user = self.get_current_user(db)
                if not user:
                    self.send_error_json("Please sign in", 401)
                    return
                item_id = int(path.split("/")[3])
                item_row = db.execute(f"SELECT owner_id FROM {items_table} WHERE id = ?", (item_id,)).fetchone()
                if not item_row:
                    self.send_error_json("Item not found", 404)
                    return
                if dict(item_row)["owner_id"] != user["id"] and user.get("role") != "admin":
                    self.send_error_json("Permission denied", 403)
                    return
                db.execute(f"DELETE FROM {items_table} WHERE id = ?", (item_id,))
                db.commit()
                self.send_json({"ok": True})
                return
            self.send_error_json("Route not found", 404)
        finally:
            db.close()


def run_server():
    initialise_database()
    server = ThreadingHTTPServer((HOST, PORT), FoundlyHandler)
    print(f"✓ VCTM Foundly Production Backend LIVE at http://{HOST}:{PORT}")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nShutting down server gracefully.")
        server.server_close()


if __name__ == "__main__":
    run_server()
