-- =============================================================
-- VCTM Foundly — Supabase Cloud PostgreSQL Database Schema
-- Run this SQL in your Supabase Dashboard: SQL Editor -> New Query
-- =============================================================

-- 1. Create Items Table
CREATE TABLE IF NOT EXISTS public.items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    location TEXT NOT NULL,
    item_date DATE NOT NULL DEFAULT CURRENT_DATE,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('Lost', 'Found')),
    status TEXT NOT NULL DEFAULT 'Open' CHECK (status IN ('Open', 'Resolved', 'Archived')),
    image_data TEXT,
    proof_question TEXT,
    owner_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    owner_name TEXT,
    owner_email TEXT,
    owner_role TEXT DEFAULT 'Student',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Create Connections & Claims Table
CREATE TABLE IF NOT EXISTS public.connections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    item_id BIGINT REFERENCES public.items(id) ON DELETE CASCADE,
    sender_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    sender_name TEXT NOT NULL,
    sender_email TEXT NOT NULL,
    sender_role TEXT DEFAULT 'Student',
    sender_phone TEXT,
    recipient_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    recipient_name TEXT NOT NULL,
    recipient_email TEXT NOT NULL,
    recipient_role TEXT DEFAULT 'Student',
    recipient_phone TEXT,
    message TEXT NOT NULL,
    status TEXT NOT NULL DEFAULT 'Pending' CHECK (status IN ('Pending', 'Accepted', 'Declined', 'Matched')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Create Profiles Table
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    campus_role TEXT DEFAULT 'Student',
    phone TEXT,
    role TEXT DEFAULT 'user',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 4. Enable Row Level Security (RLS)
ALTER TABLE public.items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.connections ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 5. RLS Policies for Items
CREATE POLICY "Public items are viewable by everyone" 
ON public.items FOR SELECT 
USING (true);

CREATE POLICY "Authenticated users can insert items" 
ON public.items FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update their own items" 
ON public.items FOR UPDATE 
USING (auth.uid() = owner_id);

CREATE POLICY "Users can delete their own items" 
ON public.items FOR DELETE 
USING (auth.uid() = owner_id);

-- 6. RLS Policies for Connections
CREATE POLICY "Users can view connections they are part of" 
ON public.connections FOR SELECT 
USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

CREATE POLICY "Authenticated users can create connection claims" 
ON public.connections FOR INSERT 
WITH CHECK (auth.role() = 'authenticated');

CREATE POLICY "Users can update connections they received or sent" 
ON public.connections FOR UPDATE 
USING (auth.uid() = sender_id OR auth.uid() = recipient_id);

-- 7. Seed Sample Items
INSERT INTO public.items (name, category, location, item_date, description, type, status, proof_question, owner_name, owner_email, owner_role)
VALUES 
('Silver Dell Inspiron Laptop', 'Electronics', 'Engineering Block Lab 204', CURRENT_DATE, '15-inch silver laptop with Python sticker on back.', 'Lost', 'Open', 'What is the lockscreen wallpaper?', 'Tarun Kumar', 'tarun@vctm.in', 'Student'),
('Dell Laptop in Black Sleeve', 'Electronics', 'Computer Lab 2nd Floor', CURRENT_DATE, 'Found silver laptop inside a neoprene black sleeve.', 'Found', 'Open', 'What brand is the charger?', 'Campus Security', 'security@vctm.in', 'Staff member'),
('Titan Gold Watch', 'Accessories', 'Library 1st Floor', CURRENT_DATE, 'Analog gold dial Titan watch with metal strap.', 'Lost', 'Open', 'What is the strap color?', 'Pooja Sharma', 'pooja@vctm.in', 'Faculty'),
('Prescription Glasses', 'Accessories', 'Seminar Hall Block B', CURRENT_DATE - 1, 'Black rectangular RayBan frame in black leather case.', 'Found', 'Open', 'What brand is on the hinge?', 'Admin Desk', 'admin@vctm.in', 'Staff member');
